### ISSUE TITLE
为什么编译打包完成后没有退出

### ISSUE THREAD

**Issue by yzw7489757** [yywc/webpack-vue#1]
![image](https://user-images.githubusercontent.com/28922129/57424177-5eca3500-7249-11e9-87b5-6ab9bc3125da.png)

**Comment by yywc** [comment]
我之前还没注意到，多谢指正，我找找原因再回复你。

**Comment by yywc** [comment]
@yzw7489757 
将 threadLoader.warmup() 预热改成下面部分，这个好像是 thread-loader 的问题，我去那边问问。
![image](https://user-images.githubusercontent.com/18376480/57462304-32df9b80-72ab-11e9-8dcd-b89bb7da991e.png)

**Comment by 1273082756** [comment]
解决了吗请问, 我也是开启预加载后, 打包完成不退出
